project:
  type: website
  output-dir: docs

navbar:
  title: "eBirdCBC"
  left:
    - text: "Home"
      href: website/index.qmd
    - text: "About eBirdCBC"
      href: website/ebirdcbc.qmd
    - text: "Field Protocol"
      href: website/fieldprotocol.qmd
    - text: "Abbotts Lagoon"
      href: website/abbottslagoon.qmd
    - text: "Tennessee Valley"
      href: website/tennesseevalley.qmd
    - text: "Contact"
      href: website/contact.qmd

format:
  html:
    theme: flatly
    fontsize: 1.3em
    css: website/styles.css
    toc: true
    page-layout: full
    grid: 
      body-width: 1500px
      gutter-width: 4em