project:
  type: website
  output-dir: ../docs
  resources:
  - images/
  - input/
  preview: 
    port: 4321
    browser: true
  render: 
    - "*.qmd"

filters: []

website:
  title: "eBirdCBC"
  reader-mode: true
  page-navigation: true
  
  navbar:
    search: FALSE
    left:
      - text: "Home"
        href: index.html
      - text: "For CBC Counters"
        menu:
          - text: "Field Protocol"
            href: fieldprotocol.html
      - text: "For Area Leaders"
        menu:
          - text: "Overall Methods"
            href: eBirdCBCmethods.html
      - text: "Examples"
        menu:
          - text: "Abbotts Lagoon"
            href: abbottslagoon.html
          - text: "Tennessee Valley"
            href: tennesseevalley.html
      - text: "Using the Program"
        menu:
          - text: "eBird CBC program"
            href: usingtheprogram.html
      - text: Contact
        href: contact.html
      
  # navbar:
  #   search: false
  #   left:
  #     - href: index.html
  #       text: Home
  #     - href: eBirdCBCmethods.html
  #       text: Methods
  #     - href: fieldprotocol.html
  #       text: Field Protocol
  #     - text: examples
  #     - href: abbottslagoon.html
  #       text: Abbotts Lagoon
  #     - href: tennesseevalley.html
  #       text: Tennessee Valley
  #     - href: ebirdcbc.html
  #       text: About
  #     - href: contact.html
  #       text: Contact

format:
  html:
    theme: flatly
    fontsize: 1.3em
    css: styles.css
    toc: true
    page-layout: full
    spacing: false
    grid: 
      body-width: 1500px
      gutter-width: 4em