---
title: "About eBirdCBC"
format: 
    html:
        css: index.css
        anchor-sections: false
---

# About eBirdCBC

eBirdCBC is a collaborative project that leverages eBird data and advanced algorithms to enhance the compilation of area lists for Christmas Bird Counts (CBCs). The project combines the expertise of Durrell Kapan and Mark Schulist, with the support of many dedicated individuals conducting eBird-powered CBCs. Examples include the Abbotts Lagoon subarea (#23) of the Point Reyes CBC and the Tennessee Valley subarea of the Southern Marin CBC.

### Background

The Christmas Bird Count (CBC) is a long-standing community science project that has been instrumental in bird conservation efforts. To encourage greater participation, it’s beneficial to bridge the traditional, primarily analog methods of the CBC with modern, digitally enabled practices like eBirding. This integration can make the CBC more accessible and engaging, attracting a broader audience and enhancing data collection.

For more information on the CBC and to find a count near you, visit the Audubon Christmas Bird Count page. To explore eBirding and how it complements the CBC, check out eBird’s official website.Purpose

### Mission

The primary mission of eBirdCBC is to:

-   Encourage more people to join Christmas Bird Counts (CBCs) by bridging the gap between eBirders, immersed in digitally enabled birding, and the Christmas Bird Count community, who primarily use analog methods in this long-standing community science project.

-   Providing tools to efficiently integrate multiple eBird checklists into the CBC area and count-circle compilation workflows.

-   Make it easy to employ the “Max-Sum”™ algorithm to differentiate overlapping and independent checklists for accurate species lists.

-   Document existing CBC community and count-circle count-area knowledge on a persistent platform (eBird).

-   Foster collaboration and innovation in bird monitoring efforts.

© 2015-2024 Durrell D. Kapan