---
title: "Home"
format: 
    html:
        css: index.css
        anchor-sections: false
---

## eBirdCBC Project

Welcome to the eBirdCBC project, a hybrid approach to modernizing the Christmas Bird Count (CBC) using eBird data and tools. Explore how we blend traditional methods with digital tools to enhance accuracy, repeatability, increase CBC participation, and the long-term value for bird conservation efforts.

### Goals

-   **Encourage Participation**: Increase engagement by providing easier and more accessible data collection tools for bird counters.
-   **Improve Accuracy**: Address challenges such as overlapping count areas and inconsistent methods with a robust data integration system.
-   **Preserve Knowledge**: Ensure long-term reproducibility and documentation of count methods and results.

### Why Use eBird for Christmas Bird Counts?

Integrating eBird into CBCs simplifies data compilation, captures local knowledge, and improves accuracy. By combining eBird lists and the MAX-SUM™ algorithm, we:

-   Eliminate double-counting and confusion.

-   Enhance repeatability and data reliability.

-   Preserve cultural and local knowledge about count areas and team deployment.

This hybrid approach ensures the long-term success of the CBC as the world’s longest-running community science project while adapting to the information age.

### About the eBirdCBC program

The eBirdCBC program helps streamline the process of compiling data for Christmas Bird Counts (CBCs). Leveraging eBird’s data collection and tracking capabilities, eBirdCBC integrates these tools with an innovative algorithm to simplify workflows, eliminate double-counting, and enhance the reproducibility of CBCs.

### Explore the Site

-   [**eBirdCBC methods**](eBirdCBCmethods.html "eBirdCBC methods")**:** Learn about the project and program methods, and the MAX-SUM™ algorithm we developed to eliminate double-counting and improve data accuracy.

-   [Field Protocol](fieldprotocol.html)**:** Dive into detailed guidelines on how to prepare, collect, and transcribe data during your CBC.

-   **Real-World Example: [Abbotts Lagoon](abbottslagoon.html):** Abbotts Lagoon, with its rich diversity of bird species, always attracts all our counters to the lagoon at the end of the day. This example showcases how careful data management combined with the MAX-SUM™ algorithm ensures accurate counts by effectively reducing double-counting and improving overall precision.

-   **Real-World Example: [Tennessee Valley](tennesseevalley.html):** Discover another real-world example of implementing eBirdCBC in the Southern Marin CBC circle.

-   **For questions** see our [Contact page](contact.qmd).

-   All this site is (c) 2015-2024 Durrell D. Kapan, please email if you would like to duplicate or modify these materials in any way.

### 
