project:
  type: website
  output-dir: ../docs
  resources: input/*
  preview: 
    port: 4321
    browser: true
  render: 
    - "*.qmd"

filters: []

website:
  title: "eBirdCBC"
  reader-mode: true
  page-navigation: true

  navbar:
    search: false
    left:
      - href: index.html
        text: Home
      - href: eBirdCBCmethods.html
        text: Methods
      - href: fieldprotocol.html
        text: Field Protocol
      - text: examples
      - href: abbottslagoon.html
        text: Abbotts Lagoon
      - href: tennesseevalley.html
        text: Tennessee Valley
      - href: ebirdcbc.html
        text: About
      - href: contact.html
        text: Contact

format:
  html:
    theme: flatly
    fontsize: 1.3em
    css: styles.css
    toc: true
    page-layout: full
    grid: 
      body-width: 1500px
      gutter-width: 4em