project:
  type: website
  output-dir: ../docs

navbar:
  title: "eBirdCBC"
  left:
    - text: "Home"
      href: index.qmd
    - text: "About eBirdCBC"
      href: ebirdcbc.qmd
    - text: "Field Protocol"
      href: fieldprotocol.qmd
    - text: "Abbotts Lagoon"
      href: abbottslagoon.qmd
    - text: "Tennessee Valley"
      href: tennesseevalley.qmd
    - text: "Contact"
      href: contact.qmd

format:
  html:
    theme: flatly
    fontsize: 1.3em
    css: styles.css
    toc: true
    page-layout: full
    grid: 
      body-width: 1500px
      gutter-width: 4em