---
title: "Contact"
format: 
    html:
        css: index.css
        anchor-sections: false
---

# Contact

### Meet the Team

-   Dr. Durrell D. Kapan: Senior Research Fellow, California Academy of Sciences. Birds sparked my lifelong journey in science. I’ve participated in CBCs since childhood in Oregon and now lead the Abbotts Lagoon subarea for the Pt. Reyes CBC and the Tennessee Valley subarea for the S. Marin CBC. Collaborating with dedicated volunteers, including youth birders and their skilled mentors, inspired the development of eBirdCBC and the MAX-SUM algorithm to address overlapping observations—particularly when counters converge at the lagoon or ocean after covering their specific areas.

-   Mark Schulist: A CBC participant since middle school, Mark is now a sophomore studying computer science at Washington University. As eBirdCBC’s primary developer, he leads application programming and protocol deployment during live CBCs. He also helped co-create the project website.

-   This project also relies on the efforts of countless volunteers on CBCs who put up with being test subjects.

-   We dedicate this work to all the bird enthusiasts who have contributed to the success of CBCs for over 123 years!

### Contact

For inquiries, please reach out to us at [ebirdcbc\@gmail.com](mailto:ebirdcbc@gmail.com)

All of this site is © 2015-2024 Durrell D. Kapan, please contact me at the email above if you would like to repackage, duplicate or modify these materials in any way.
